#! configuration.yml
application:
  port: 8000
  host: localhost
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"

redis_uri: "redis://127.0.0.1:6379"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
